stages:
  - build
  - deploy

variables:
  IMAGE_TAG: "registry.gitlab.com/gatara.ai/b2b-cold-outreach:latest"

# Build Docker image and push to GitLab Container Registry
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

# Deploy to VPS
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $VPS_USER@$VPS_HOST "
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        cd ~/projects/products/campaigns/b2b-cold-outreach &&
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml down &&
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull &&
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
      "
