version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env  # Loads variables from .env (same dir as docker-compose.yml)
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py makemigrations &&
            python manage.py makemigrations clients campaign api &&
            python manage.py migrate clients campaign api &&
            python manage.py migrate &&
            gunicorn dcrm.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

volumes:
  static_volume: